[alias]
xtask = "run --package xtask --"

[build]
artifact-dir = "target/artifacts"

[unstable]
unstable-options = true

[target.'cfg(target_os = "linux")']
linker = ".cargo/sima-linker.sh"
rustflags = ["-C", "prefer-dynamic", "-C", "link-arg=-Wl,-rpath,$ORIGIN"]
